name: ci
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  release:
    types:
      - published

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.12.0
      - uses: pnpm/setup@v2.1.0
        with:
          install: false
          cache: true
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          enable_go: true
          nvmrc_path: './.nvmrc'
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build libraries
        run: 'pnpm build'
      - name: store libraries archives
        uses: actions/upload-artifact@v7
        with:
          name: archives
          path: |
            **/dist
            !node_modules

  lint-pnpm:
    name: 'lint-pnpm'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.12.0
      - uses: pnpm/setup@v2.1.0
        with:
          install: false
          cache: true
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm format:check

  test-pnpm:
    name: 'test-pnpm'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.12.0
      - uses: pnpm/setup@v2.1.0
        with:
          install: false
          cache: true
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  type-check:
    name: 'type-check'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.12.0
      - uses: pnpm/setup@v2.1.0
        with:
          install: false
          cache: true
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm type-check

  release:
    name: 'release'
    needs: 'build'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC trusted publishing
      contents: read
    if: ${{ github.event.release.tag_name }}
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.12.0
      - uses: pnpm/setup@v2.1.0
        with:
          install: false
          cache: true
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          enable_go: true
          nvmrc_path: './.nvmrc'
      - name: Download archive
        uses: actions/download-artifact@v8
        with:
          name: archives
      - name: Publish npm package
        run: go run ./scripts/npm-publish/npm-publish.go -tag=${{ github.event.release.tag_name }}
